addons:
  ssh_known_hosts: russellhay.com
language: go
go:
- tip
install:
- go get -u -v github.com/spf13/hugo
script:
- hugo
notifications:
  email:
    on_failure: always
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/stainless/
  on:
    branch: master
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
before_install:
- openssl aes-256-cbc -K $encrypted_2cb09c647182_key -iv $encrypted_2cb09c647182_iv
  -in deploy_rsa.enc -out deploy_rsa -d
