baseurl = "https://stainless.io/"
languageCode = "en-us"
title = "Stainless"
theme = "paper"
Paginate = 10
preserveTaxonomyNames = true
enableRobotsTXT = true
pygmentsCodefences = true
googleAnalytics = "UA-514101-28"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
tag = "tags"
author = "authors"

[params]
copyright="&copy; 2019 Russell Hay and respective authors"
disqusShortname="stainless"
enableDisqus = true
twitter = "stainlessio"
iconFont = "font-awesome"
author = "Russell Hay"
authorId = "https://russellhay.com/"

[social]
twitter = "https://twitter.com/stainlessio"
github = "https://github.com/RussTheAerialist"
instagram = "http://instagram.com/therealrussellhay"
